"""
Telegram Bot for the Floor Plan 10x5 Project.

This bot allows users to interact with the project via Telegram:
- /start - Welcome message
- /floorplan - Get the floor plan image/info
- /download_step - Get the STEP file
- /download_stl - Get the STL file
- /help - Show available commands

Set the TELEGRAM_BOT_TOKEN environment variable before running.
"""

import os
import logging
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(
        "Welcome to the Floor Plan 10x5 Bot!\n\n"
        "This bot lets you access floor plan files generated by the project.\n"
        "Use /help to see available commands."
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(
        "Available commands:\n"
        "/start - Welcome message\n"
        "/floorplan - Get floor plan info\n"
        "/download_step - Download the STEP file\n"
        "/download_stl - Download the STL file\n"
        "/help - Show this help message"
    )


async def floorplan(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(
        "Floor Plan 10x5m\n"
        "A 10x5 meter plate generated as STEP and STL files.\n"
        "Use /download_step or /download_stl to get the files."
    )


async def download_step(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    step_path = os.path.join(PROJECT_DIR, "planimetria_10x5.step")
    if os.path.exists(step_path):
        await update.message.reply_document(
            document=open(step_path, "rb"),
            filename="planimetria_10x5.step",
            caption="Floor Plan 10x5 - STEP file",
        )
    else:
        await update.message.reply_text("STEP file not found. Run the generator first.")


async def download_stl(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    stl_path = os.path.join(PROJECT_DIR, "planimetria_10x5.stl")
    if os.path.exists(stl_path):
        await update.message.reply_document(
            document=open(stl_path, "rb"),
            filename="planimetria_10x5.stl",
            caption="Floor Plan 10x5 - STL file",
        )
    else:
        await update.message.reply_text("STL file not found. Run the generator first.")


def main() -> None:
    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    if not token:
        logger.error(
            "TELEGRAM_BOT_TOKEN environment variable not set. "
            "Export it before running: export TELEGRAM_BOT_TOKEN='your-token-here'"
        )
        raise SystemExit(1)

    application = Application.builder().token(token).build()

    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("floorplan", floorplan))
    application.add_handler(CommandHandler("download_step", download_step))
    application.add_handler(CommandHandler("download_stl", download_stl))

    logger.info("Bot started. Press Ctrl+C to stop.")
    application.run_polling(allowed_updates=Update.ALL_TYPES)


if __name__ == "__main__":
    main()
